Models/Basket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CS10_Project_Fisketorvet_V1.Models
{
    public class Basket
    {
        //List of an array, each array holds the product and its quantity like this array[0] = productid, array[1]= quantity
        //To add/remove items use a method
        const string JsonBaskets = @"Data\Baskets.json";
        public static Dictionary<int, Basket> Catalog = Helpers.JsonFileHelper<Basket>.ReadJson(JsonBaskets);
        List<int[]> _items { get; }
        int _id;

        public List<int[]> Items
        {
            get; set;
        }
        public int ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        public static void Create(Basket basket)
        {
            for(int i=1; i<=Catalog.Count+1; i++)
            {
                if (!Catalog.ContainsKey(i))
                {
                    basket.ID = i;
                    basket.Items = new List<int[]>();
                    Catalog.Add(i, basket);
                    break;
                }
            }
            UpdateCatalog();
        }
        public void Add(int id, int quantity)
        {
            if (quantity > 0)
            {
                int[] newarray = new int[2] { id, quantity };
                if (Items.Count == 0)
                {
                    Items.Add(newarray);
                    UpdateCatalog();
                    return;
                }
                foreach (int[] i in Items)
                {
                    if (i[0] == id)
                    {
                        i[1] += quantity;
                        UpdateCatalog();
                        return;
                    }
                }
                Items.Add(newarray);
                UpdateCatalog();
                return;
            }
            else if(quantity<0)
            {
                if (Items.Count == 0) return;
                foreach (int[] i in Items)
                {
                    if (i[0] == id)
                    {
                        i[1] += quantity;
                        if (i[1] <= 0) Remove(id);
                        UpdateCatalog();
                        return;
                    }
                }
            }
        }
        public void ChangeQuantity(int id, int quantity)
        {
            int[] newarray = new int[2] { id, quantity };
            foreach (int[] i in Items)
            {
                if(i[0] == newarray[0])
                {
                    i[1] = newarray[1];
                    break;
                }
            }
            UpdateCatalog();
        }
        public void Remove(int id)
        {
            foreach(int[] i in Items)
            {
                if(i[0] == id)
                {
                    i[1] = 0;
                    Items.Remove(i);
                    break;
                }
            }
            UpdateCatalog();
        }
        public static Basket GetBasket(int id)
        {
            return Catalog[id];
        }
        public void ClearBasket()
        {
            Items.Clear();
            Helpers.JsonFileHelper<Basket>.WriteToJson(Catalog, JsonBaskets);
        }
        public static void UpdateCatalog()
        {
            Helpers.JsonFileHelper<Basket>.WriteToJson(Catalog, JsonBaskets);
        }
    }
}

Pages/ShoppingCart/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace CS10_Project_Fisketorvet_V1.Pages
{
    public class BasketModel : PageModel
    {
        private static BasketModel _instance;

        public static BasketModel Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new BasketModel();
                }
                return _instance;
            }
        }
        [BindProperty]
        [Required(ErrorMessage = "You need to link a bank account to continue")]
        public string NoBankAccountChecker
        {
            get;set;
        }

        public IActionResult OnGet()
        {
            return Page();
        }
        public IActionResult OnPostRemove(int p)
        {
            ShoppingCart.BasketHelper.RemoveFromBasket(p);
            return Page();
        }
        public IActionResult OnPostCheckout()
        {
            return RedirectToPage("/ShoppingCart/Checkout");
        }
        public IActionResult OnPostPlus(int p)
        {
            ShoppingCart.BasketHelper.AddToBasket(p, 1);
            return Page();
        }
        public IActionResult OnPostMinus(int p)
        {

            ShoppingCart.BasketHelper.AddToBasket(p, -1);
            return Page();
        }
        public IActionResult OnPostFail()
        {
            if (!ModelState.IsValid)
                return Page();
            return Page();
        }
        public static double CalculateItemsTotalPrice()
        {
            double subtotal = 0;
            foreach (int[] p in Basket.GetBasket(Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].BasketID).Items)
            {
                subtotal = subtotal + (Models.Product.GetProduct(p[0], Models.Product.ProductCatalog).ProductPrice*p[1]);
            }
            return subtotal;
        }
        public static int CalculateItemsNr()
        {
            int total = 0;
            foreach (int[] p in Basket.GetBasket(Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].BasketID).Items)
            {
                total = total + (1 * p[1]);
            }
            return total;
        }
    }
}

Pages/ShoppingCart/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.ShoppingCart
{
    public class CheckoutModel : PageModel
    {
        public static bool InsuficientFunds = false;
        public static bool CompletedTransaction = false;
        [BindProperty]
        [Required(ErrorMessage ="The Zip code is required")]
        [Range(1000,9999)]
        public int ZIP
        {
            get; set;
        }
        [Required(ErrorMessage = "The street is required")]
        [BindProperty]
        [MaxLength(50)]
        public string Street
        {
            get;set;
        }
        [Required(ErrorMessage = "The street number is required")]
        [BindProperty]
        public string StreetNR
        {
            get; set;
        }
        public IActionResult OnGet()
        {
            InsuficientFunds = false;
            CompletedTransaction = false;
            return Page();
        }
        public IActionResult OnPost(double amount)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].Account.CanPay(amount))
            {
                #region Payment
                Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].Account.Pay(amount);
                #endregion
                #region Order creation
                Models.Order order = new Models.Order();
                order.Street = Street;
                order.StreetNR = StreetNR;
                order.ZIP = ZIP;
                order.Items = GetBasketItems(Models.Basket.GetBasket(Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].BasketID).Items);
                order.OwnerID = LoggedInUser.CurrentUser.User[0];
                order.Price = CalculateTotalPrice(BasketModel.CalculateItemsTotalPrice(), 10);
                Models.Order.Create(order);
                #endregion
                #region Clearing the basket
                Models.Basket.GetBasket(Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].BasketID).ClearBasket();
                #endregion
                CompletedTransaction = true;
                return Page();
            }
            else
            {
                InsuficientFunds = true;
                return Page();
            }
        }

        public static double CalculateTotalPrice(double price, double discount)
        {
            return price -= price * 0.01 * discount;
        }
        public static List<int[]> GetBasketItems (List<int[]> basket)
        {
            List<int[]> list = new List<int[]>();
            foreach(int[] i in basket)
            {
                list.Add(i);
            }
            return list;
        }
    }
}

Pages/ShoppingCart/Basket.cshtml
@page "Basket"
@using CS10_Project_Fisketorvet_V1.Pages.LoggedInUser
@model CS10_Project_Fisketorvet_V1.Pages.BasketModel
@{
    ViewData["Title"] = "Shopping Cart";
}


@{
    if (LoggedInUser.CurrentUser.Exists && LoggedInUser.CurrentUser.HasBasket)
    {
        <div class="container">
            <div class="row py-3 justify-content-center">
                
                <div class="col-10"><h5 class="font-weight-normal">@Models.Customer.Catalog[CurrentUser.User[0]].FirstName's Basket </h5></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-10">
                    <table class="table mb-0">
                        <thead>
                        <tr class="table-light">
                            <th></th>
                            <th>Product</th>
                            <th class="text-right">Price</th>
                            <th class="text-center">Amount</th>
                            <th class="text-center">Remove</th>
                        </tr>


                        </thead>
                        <tbody>

                        @foreach (int[] i in Models.Basket.Catalog[Models.Customer.Catalog[LoggedInUser.CurrentUser.User[0]].BasketID].Items)
                        {
                            Models.Product item = Models.Product.GetProduct(i[0], Models.Product.ProductCatalog);
                            <tr>
                                <td><img src="/images/@item.ImagePath" style="max-width: 48px; max-height: 48px;"/></td>
                                <td>@item.ProductName</td>
                                <td class="text-right">@item.ProductPrice kr</td>
                                <td class="text-center">
                                    <div class="form-inline justify-content-center">
                                        <div>
                                            <form method="post">
                                                <input type="submit" value="-" class="btn btn-light btn-sm" asp-page-handler="minus" asp-route-p="@item.ProductId"/>
                                            </form>
                                        </div>
                                        <div class="mx-3">@i[1]</div>
                                        <div>
                                            <form method="post">
                                                <input type="submit" value="+" class="btn btn-light btn-sm" asp-page-handler="plus" asp-route-p="@item.ProductId"/>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <form method="post">
                                        <input type="submit" value="X" class="btn btn-outline-danger btn-sm" asp-page-handler="remove" asp-route-p="@item.ProductId"/>
                                    </form>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td class="text-right">
                                <div class="font-weight-bold">
                                    Total price:
                                    <br/>
                                    @BasketModel.CalculateItemsTotalPrice() kr
                                </div>
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                    
                    <div class="row justify-content-center justify-content-sm-end pr-5">
                        @{
                            if (LoggedInUser.CurrentUser.HasBankAccount)
                            {
                                <form method="post">
                                    <input type="submit" asp-page-handler="checkout" value="Proceed to payment" class="btn btn-secondary" />
                                </form>
                            }
                            else
                            {
                                <form method="post">
                                    <input type="submit" asp-page-handler="fail" value="Proceed to payment" class="btn btn-secondary" />
                                    <span asp-validation-for="@Model.NoBankAccountChecker" class="text-danger"></span>
                                </form>
                            }
                        }

                    </div>
                </div>
            </div>
        </div>
        ;
    }
    else if (LoggedInUser.CurrentUser.Exists)
    {
        <div>
            You do not have any items in your basket
        </div>
    }
    else
    {
        <div>
            You must be logged in to view your basket
        </div>
    }
}

Pages/ShoppingCart/Checkout.cshtml
@page "Checkout"
@model CS10_Project_Fisketorvet_V1.Pages.ShoppingCart.CheckoutModel
@{
    ViewData["Title"] = "Checkout";
    int nr = BasketModel.CalculateItemsNr();
    double price = BasketModel.CalculateItemsTotalPrice();
    double total = @CheckoutModel.CalculateTotalPrice(price, 10);
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-10 text-center mb-3">
            <h5>Checkout</h5>
        </div>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-10">
            @{
                if (CheckoutModel.CompletedTransaction)
                {
                    <span>Your order has been placed</span>
                    <br/>
                    <span>Thank you for your purchase!</span>
                }
                else if (CheckoutModel.InsuficientFunds)
                {
                    <span>It seems that you do not have the required funds to complete this transaction</span>
                }
                else
                {
                    <div class="row justify-content-center">
                        <div class="col col-md-5 pt-3">
                            <div class="pb-3">
                                You are about to purchase @nr
                                @{if (nr > 1)
                                  {
                                      <span>items</span>}
                                  else
                                  {
                                      <span>item</span>}
                                }
                            </div>
                            <div>
                                Items price: @price kr
                                <br>
                                Discount: 10% (Members' club)
                                <br>
                                Total: @total kr
                            </div>

                        </div>
                        <div class="col col-md-5">
                            <div>
                                <form method="post">

                                    <div class="form-group">
                                        <label asp-for="@Model.ZIP" class="col-form-label-sm mb-0">ZIP:</label>
                                        <input asp-for="@Model.ZIP" type="number" class="form-control"/>
                                        <span asp-validation-for="@Model.ZIP" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.Street" class="col-form-label-sm mb-0">Street:</label>
                                        <input asp-for="@Model.Street" type="text" class="form-control"/>
                                        <span asp-validation-for="@Model.Street" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.StreetNR" class="col-form-label-sm mb-0">StreetNR:</label>
                                        <input asp-for="@Model.StreetNR" type="text" class="form-control"/>
                                        <span asp-validation-for="@Model.StreetNR" class="text-danger"></span>
                                    </div>
                                    <div>
                                        <input type="submit" class="btn btn-dark" value="Place order" asp-route-amount="@total"/>
                                        <a asp-page="/ShoppingCart/Basket" class="btn btn-outline-dark">Back to basket</a>
                                    </div>
                                </form>
                            </div>
                            <div class="col"></div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>