Models/Store.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CS10_Project_Fisketorvet_V1.Models
{
    public class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
    }
}

Pages/Stores/AddNewProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class AddNewProductModel : PageModel
    {
        IProductRepository products;

        public AddNewProductModel(IProductRepository prodRepo)
        {
            products = prodRepo;
        }

        [BindProperty]
        public Product NewProduct { get; set; }

        public IActionResult OnGet(int storeId)
        {
            NewProduct = new Product() { StoreID = storeId };
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                products.AddNewProduct(NewProduct);
                return RedirectToPage("Stores");
            }
            return Page();

        }
    }
}

Pages/Stores/DeleteProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class DeleteProductModel : PageModel
    {
        IProductRepository products;

        public DeleteProductModel(IProductRepository prodRepo)
        {
            products = prodRepo;
        }

        [BindProperty]
        public Product Product { get; set; }

        [BindProperty]
        public int StoreId { get; set; }

        public void OnGet(int prodId, int storeId)
        {
            Product = products.GetProduct(prodId);
            StoreId = storeId;
        }

        public IActionResult OnPost()
        {
            products.DeleteProduct(Product.ProductId);
            return Redirect($"/Stores/StoreProductAdmin/{StoreId}");
        }
    }
}

Pages/Stores/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class EditProductModel : PageModel
    {
        IProductRepository products;

        public EditProductModel(IProductRepository prodRepo)
        {
            products = prodRepo;
        }

        [BindProperty]
        public Product Product { get; set; }

        [BindProperty]
        public int StoreId { get; set; }

        public void OnGet(int prodId, int storeId)
        {
            Product = products.GetProduct(prodId);
            StoreId = storeId;
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                products.UpdateProduct(Product);
                return Redirect($"/Stores/StoreProductAdmin/{StoreId}");
            }

            return Page();
        }

        
    }
}

Pages/Stores/ShowStore.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using CS10_Project_Fisketorvet_V1.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class ShowStoreModel : PageModel
    {
        IProductRepository products;
        IStores stores;
        [BindProperty]
        [Required(ErrorMessage = "You must be logged in to add to the basket")]
        public int NonExistentUser
        {
            get;set;
        }
        static int storeid;
        public static int checkedproductid;
        public Store Store { get; set; }
        public List<Product> Products { get; set; }

        public ShowStoreModel(IStores storesRepo, IProductRepository productsRepo)
        {
            stores = storesRepo;
            products = productsRepo;
        }

        public IActionResult OnGet(int storeId)
        {
            Store = stores.AllStores()[storeId];
            Products = products.GetStoreProducts(storeId);
            storeid = storeId;
            return Page();
        }
        public IActionResult OnPost(int p)
        {
            if (!ModelState.IsValid)
            {
                Store = stores.AllStores()[storeid];
                Products = products.GetStoreProducts(storeid);
                checkedproductid = p;
                return Page();
            }
            return Page();
        }
        public IActionResult OnPostAdd(int p)
        {
            Store = stores.AllStores()[storeid];
            Products = products.GetStoreProducts(storeid);
            ShoppingCart.BasketHelper.AddToBasket(p, 1);
            return Page();
        }
    }
}

Pages/Stores/StoreProductAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class StoreAdminModel : PageModel
    {
        IProductRepository products;
        IStores stores;

        public StoreAdminModel(IProductRepository prodRepo, IStores storeRepo)
        {
            products = prodRepo;
            stores = storeRepo;
        }

        public List<Product> Products { get; set; }

        [BindProperty(SupportsGet =true)]
        public int StoreId { get; set; }

        public Store Store { get; set; }

        public void OnGet(int storeId)
        {
            StoreId = storeId;
            Store = stores.AllStores()[StoreId];
            Products = products.GetStoreProducts(storeId);
        }

        public void OnPostDelete(int prodId)
        {
            products.DeleteProduct(prodId);
            OnGet(StoreId);
        }
    }
}

Pages/Stores/Stores.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS10_Project_Fisketorvet_V1.Interfaces;
using CS10_Project_Fisketorvet_V1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CS10_Project_Fisketorvet_V1.Pages.Stores
{
    public class StoresModel : PageModel
    {
        public Dictionary<int,Store> Stores { get; private set; }
        IStores repo;
        [BindProperty(SupportsGet =true)]
        public string FilterCriteria { get; set; }
        public StoresModel(IStores repository)
        {
            repo = repository;
        }

        public IActionResult OnGet()
        {
            Stores = repo.AllStores();
            if (!string.IsNullOrEmpty(FilterCriteria))
            {
                Stores = repo.FilterStores(FilterCriteria);
            }
            return Page();
        }
    }
}

Pages/Stores/AddNewProduct.cshtml
@page "{storeId}"
@model CS10_Project_Fisketorvet_V1.Pages.Stores.AddNewProductModel
@{
    ViewData["Title"] = "New product";
}

<div class="container">
    <div class="row justify-content-sm-center">
        <h5 class="lead">Add a new product to your store</h5>
    </div>

    @if (ModelState.IsValid)
    {
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteMadalLongTitle">Delete item</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>@Model.NewProduct.ProductName was added to your store.</p>
                    </div>
                    <div class="modal-footer">
                        <a asp-page="StoreProductAdmin" asp-route-storeId="@Model.NewProduct.StoreID">OK</a>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="row justify-content-center">
        <div class="col-sm-8">
            <form method="post" class="form-group">
                <div class="form-group">
                    <label asp-for="@Model.NewProduct.ProductName" class="col-form-label-sm mb-0">Name:</label>
                    <input asp-for="@Model.NewProduct.ProductName" type="text" class="form-control" />
                    <span asp-validation-for="@Model.NewProduct.ProductName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.NewProduct.ProductDescription" class="col-form-label-sm mb-0">Description:</label>
                    <textarea asp-for="@Model.NewProduct.ProductDescription" type="text" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.NewProduct.ProductPrice" class="col-form-label-sm mb-0">Price:</label>
                    <input asp-for="@Model.NewProduct.ProductPrice" type="text" class="form-control" />
                    <span asp-validation-for="@Model.NewProduct.ProductPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.NewProduct.ImagePath" class="col-form-label-sm mb-0">Image path:</label>
                    <input asp-for="@Model.NewProduct.ImagePath" type="text" class="form-control" />
                </div>

                <input asp-for="@Model.NewProduct.StoreID" type="hidden" />

                <div class="row">
                    <div class="col">
                        <input type="submit" value="Add item to catalog" class="btn btn-secondary btn-sm" />

                        <a asp-page="StoreProductAdmin" asp-route-storeId="@Model.NewProduct.StoreID" class="btn btn-outline-secondary btn-sm">Return to product overview</a>
                    </div>

                </div>


            </form>

        </div>
    </div>

</div>

Pages/Stores/DeleteProduct.cshtml
@page "{prodId}"
@model CS10_Project_Fisketorvet_V1.Pages.Stores.DeleteProductModel
@{
}

<div class="container">
    <div class="row justify-content-sm-center py-3">
        <h5 class="text-danger">You are about to delete the following product from your store.</h5>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-8">

            <div class="row justify-content-left border border-danger p-2">
                <div class="col-auto">
                    <img src="/images/@Model.Product.ImagePath" style="max-height: 110px;"/>
                </div>
                <div class="col">
                    <div class="row justify-content-between">
                        <div class="col">
                            <h5>@Model.Product.ProductName</h5>
                        </div>
                        <div class="col text-right">
                            <h5>@Model.Product.ProductPrice kr.</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p>@Model.Product.ProductDescription</p>
                        </div>
                    </div>
                </div>
            </div>

            <form method="post" class="form-group pt-3">
                <input asp-for="@Model.Product.StoreID" type="hidden"/>
                <input asp-for="@Model.Product.ProductId" type="hidden"/>

                <div class="row">
                    <div class="col">
                        <input type="submit" value="Delete product" class="btn btn-danger btn-sm"/>
                        <a asp-page="StoreProductAdmin" asp-route-storeId="@Model.StoreId" class="btn btn-outline-secondary btn-sm">Return to product overview</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Pages/Stores/EditProduct.cshtml
@page "{prodId}"
@model CS10_Project_Fisketorvet_V1.Pages.Stores.EditProductModel
@{
    ViewData["Title"] = "Edit product";
}

<div class="container">
    <div class="row justify-content-sm-center">
        <h5 class="lead">Editing: @Model.Product.ProductName</h5>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-8">
            
            

            <form method="post" class="form-group">
                <div class="form-group">
                    <label asp-for="@Model.Product.ProductName" class="col-form-label-sm mb-0">Name:</label>
                    <input asp-for="@Model.Product.ProductName" type="text" class="form-control"/>
                    <span asp-validation-for="Product.ProductName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Product.ProductDescription" class="col-form-label-sm mb-0">Description:</label>
                    <textarea asp-for="@Model.Product.ProductDescription" type="text" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Product.ProductPrice" class="col-form-label-sm mb-0">Price:</label>
                    <input asp-for="@Model.Product.ProductPrice" type="text" class="form-control"/>
                    <span asp-validation-for="Product.ProductPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row justify-content-left">
                        <div class="col-auto">
                            <img src="/images/@Model.Product.ImagePath" style="max-height: 110px;"/>
                        </div>
                        <div class="col">
                            <label asp-for="@Model.Product.ImagePath" class="col-form-label-sm mb-0">Image Path:</label>
                            <input asp-for="@Model.Product.ImagePath" type="text" class="form-control" />
                        </div>
                    </div>
                </div>

                <input asp-for="@Model.Product.StoreID" type="hidden"/>
                <input asp-for="@Model.Product.ProductId" type="hidden"/>

                <div class="row">
                    <div class="col justify-content-start">
                        <input type="submit" value="Confirm changes" class="btn btn-secondary btn-sm" />
                        <a asp-page="StoreProductAdmin" asp-route-storeId="@Model.StoreId" class="btn btn-outline-dark btn-sm">Return to product overview</a>
                    </div>
                </div>

            </form>

        </div>
    </div>

</div>

Pages/Stores/ShowStore.cshtml
@page 
@using Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments
@using CS10_Project_Fisketorvet_V1.Pages.LoggedInUser
@model CS10_Project_Fisketorvet_V1.Pages.Stores.ShowStoreModel
@{
    ViewData["Title"] = $"{Model.Store.Name}";
}

<div class="container">
    <div class="row pb-3">
        <div class="col px-2" >
            <a asp-page="Stores" class="text-dark font-weight-normal"><span class="iconify pb-1" data-icon="ic:baseline-arrow-back-ios-new" data-inline="false"></span>Back to stores</a>
        </div>
        <div class="col text-right">
            @if (CurrentUser.User[1] == 1)
            {
                <a asp-page="StoreProductAdmin" asp-route-storeId="@Model.Store.Id" class="btn btn-dark">Product administration</a>
            }
        </div>

    </div>
    <div class="row">
        <div class="col-md-3 col-sm-12">
            <h5>Welcome to @Model.Store.Name</h5>
        </div>
        <div class="col-md-7">
            <p>@Model.Store.Description</p>
        </div>
        <div class="col-sm-2 text-center">
            <img src="~/images/@Model.Store.ImageName" style="max-height: 110px"/>
        </div>
    </div>

    <hr/>
    <div class="row">
        @foreach (var p in Model.Products)
        {
            <div class="col col-sm-4 col-md-3">
                <div class="card card-product">
                    <div class="card-body py-1 px-2">
                        <h6 class="card-title mb-2 text-center">@p.ProductName</h6>
                        <div class="d-flex justify-content-center my-2">
                            <img src="/images/@p.ImagePath" style="max-height: 110px;"/>
                        </div>
                        <p class="card-text font-weight-light mb-2">
                            @if (!string.IsNullOrEmpty(p.ProductDescription))
                            {
                                @p.ProductDescription
                            }
                            else
                            {
                                <span>&nbsp;
                                </span>
                            }
                            
                        </p>
                        <ul class="m-0 p-1">
                            <li class="row justify-content-start m-0 pb-0">
                                <p style="text-align: right" class="mb-0">@p.ProductPrice kr.</p>
                            </li>
                            <li class="row justify-content-end m-0 p-0">
                                @{
                                    if (LoggedInUser.CurrentUser.Exists)
                                    {
                                        <form method="post">
                                            @*<input type="submit" class="btn border-0" asp-page-handler="add" asp-route-p="@p.ProductId" value="Add to basket"/>*@
                                            <button type="submit" class="btn btn-lg border-0 p-0 mb-2 mr-3" asp-page-handler="add" asp-route-p="@p.ProductId"><span class="iconify" data-icon="emojione-monotone:shopping-cart" data-inline="false"></span></button>
                                        </form>
                                    }
                                    else
                                    {
                                        <form method="post">
                                            @*<span class="iconify" data-icon="emojione-monotone:shopping-cart" data-inline="false"></span>
                                                <input type="submit" class="btn border-0" asp-route-p="@p.ProductId" value="Add to basket" />*@
                                            <button type="submit" class="btn btn-lg border-0 p-0 mb-2 mr-3" asp-route-p="@p.ProductId"><span class="iconify" data-icon="emojione-monotone:shopping-cart" data-inline="false"></span></button>
                                            @{
                                                if (p.ProductId == ShowStoreModel.checkedproductid)
                                                {
                                                    <span asp-validation-for="@Model.NonExistentUser" class="text-danger"></span>;
                                                }
                                            }
                                        </form>
                                    }
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>



</div>

Pages/Stores/StoreProductAdmin.cshtml
@page "{storeId}"
@model CS10_Project_Fisketorvet_V1.Pages.Stores.StoreAdminModel
@{
    ViewData["Title"] = "Product administration";
}

<div class="container">
    <div class="row justify-content-sm-center"> @*Title*@
        <div class="col-md-10">
            <div class="row">
                <div class="col-md px-3">
                    <a asp-page="ShowStore" asp-route-storeId="@Model.StoreId" class="text-dark font-weight-normal"><span class="iconify pb-1" data-icon="ic:baseline-arrow-back-ios-new" data-inline="false"></span>Back to @Model.Store.Name</a>
                </div>
                <div class="col-md">
                    <h5 class="lead text-center">Store administration for: @Model.Store.Name</h5>
                </div>
                <div class="col-md"></div>
                
            </div>
            
        </div>

    </div>
    <div class="row justify-content-center pb-3 px-3">
        @*Search and Add*@
        <div class="col-md-5 pb-2 pb-md-1">
            <div class="d-flex justify-content-md-start justify-content-center">
                <form method="get" class="form-inline">
                    <input type="text" placeholder="Search product" class="form-control searchbar-custom" />
                </form>

            </div>

        </div>
        <div class="col-md-5">
            <div class="d-flex justify-content-md-end justify-content-center">
                <a asp-page="AddNewProduct" asp-route-storeId="@Model.StoreId" class="btn btn-secondary">Add new product</a>
            </div>
        </div>
    </div>


    <div class="row justify-content-center mx-0"> @*Product table*@
        <div class="col-10 justify-content-center">
            <div class="table-responsive-sm">
                <table class="table table-sm table-borderless table-hover">
                    <thead class="table-secondary">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.Products)
                        {
                            <tr>
                                <td>@product.ProductId</td>
                                <td>@product.ProductName</td>
                                <td>@product.ProductDescription</td>
                                <td>@product.ProductPrice</td>
                                <td class="text-right">
                                    <a asp-page="EditProduct" asp-route-prodId="@product.ProductId" asp-route-storeId="@product.StoreID" class="btn btn-outline-dark btn-sm">Edit</a>
                                </td>
                                <td class="text-right">
                                    <a asp-page="DeleteProduct" asp-route-prodId="@product.ProductId" asp-route-storeId="@product.StoreID" class="btn btn-outline-danger btn-sm">Delete</a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Pages/Stores/Stores.cshtml
@page
@model CS10_Project_Fisketorvet_V1.Pages.Stores.StoresModel
@{ 
}

<h1 class="text-center">Stores</h1>
<div class="container">
    <div class="row pb-3">
        <div class="col-md-8"></div>
        <div class="col-md-4 justify-content-md-end justify-content-center">
            <form method="get" class="form-inline">

                <input type="text" asp-for="FilterCriteria" placeholder="Search" class="form-control searchbar-custom mr-2" />
                <input type="submit" value="Filter" class="form-control btn-sm" />

            </form>
        </div>
    </div>

    <div class="row justify-content-center">
        @foreach (var item in Model.Stores)
        {
            <div class="col col-sm-4 col-md-3 justify-content-center">
                <a asp-page="ShowStore" asp-route-storeId="@item.Value.Id" class="text-dark">
                    <div class="card card-product text-center pt-2">
                        <div class="d-flex justify-content-center">
                            <div style="height: 110px; width: 110px; display: flex; justify-content: center; align-items: center;">
                                <img src='~/images/@item.Value.ImageName' class="mw-100 mh-100">
                            </div>
                        </div>
                        <h5 class="text-center flex-column font-weight-normal">@item.Value.Name</h5>
                    </div>
                </a>
            </div>
        }
    </div>
</div>